#!/usr/bin/env bash

cd `dirname $0`

source .env



usage() {
	echo Usage: $0
	exit 0
}



deploy() {
	echo デプロイ開始

	echo
	echo [1] Program Store...
	rsync -av --delete ./ ${DEPLOY_HOST}:${DEPLOY_APP_PATH} --rsync-path="${DEPLOY_RSYNC_PATH:-rsync}" --exclude=.env* --exclude=deploy --exclude=README.md --exclude=.git* --exclude=.DS_Store

	echo
	echo デプロイ完了
}



if [ "${DEPLOY_APP_PATH}" == "" ] ; then
	usage
elif [ "$1" == "-h" -o "$1" == "--help" ] ; then
	usage
else
	deploy
fi
